language: python
python:
  - 2.7
  - 3.5
sudo: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -f -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -c conda-forge -n test-environment python=$TRAVIS_PYTHON_VERSION nansat scipy basemap nose coveralls
  - source activate test-environment
  - python setup.py install

script:
  - coverage run --omit=nansatmap/tests.py --source=nansatmap setup.py test

after_success:
  - coveralls


