---
- hosts: nansatmap
  roles:
    - {role: geo-spaas-vagrant/provisioning/roles/conda}
    - {role: nansatmap}
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
