---
- hosts: nansatmap
  roles:
    - role: andrewrothstein.miniconda
      miniconda_escalate: no
      miniconda_parent_dir: /home/vagrant
      miniconda_make_sys_default: yes
    - role: andrewrothstein.conda-env
      conda_env_name: py3nansat
      conda_env_environment: conda_env_requirements.yml
      conda_env_conda_dir: /home/vagrant/anaconda
      conda_env_escalate: no
      conda_env_activate_for_login_shell: yes
    - nansatmap
